### PR TITLE
not using assetdatabase copyasset for non fx layers

### PR DESCRIPTION
**Pull request by Neuru5278**
Non FX layers are being copied and assigned incorrectly when they are sub-assets. This is caused by running it after a manual bake on a modular avatar.

### CODE REVIEW

**Comment by d4rkc0d3r** [comment]
I used to do that but it broke gogo loco which is why I reverted back to use AssetDatabase.CopyAsset() for non fx layers, see: https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/commit/1c55ca9b67f5eb3988dac7b4c127b2f1ba286682

**Comment by Neuru5278** [comment]
What kind of issues will this fix cause with gogo loco?

**Comment by d4rkc0d3r** [comment]
My friend:
> I think your layer merger fucks up GoGo locomotion
seems like something gets fucked when you jump
hips get stuck rotated oddly
> looks like it's related to the falling animation
since small jump worlds, I can't get it to trigger
and if I disable falling animations in GoGo, it no longer breaks
so that's definitely the place to look

Me:
> I'll make a test version for you real quick that does the old animator copy for the non fx layers to see if its really that part that breaks

My friend:
> no more break

That said, I could check if AssetDatabase.IsSubAsset() is true and only then do it the other way.

**Comment by d4rkc0d3r** [comment]
v2.3.2 now uses the deep copy instead of AssetDatabase.CopyAsset if the controller is a sub asset

**Pull request closed without merging**
